# Generated by Django 4.1.2 on 2022-10-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='cotes',
            new_name='votes',
        ),
    ]
